/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'StateAuditJob': CronHandler<{ topic: 'notification'; data: { templateId: string; email: string; templateData: Record<string, unknown> } }>
    'ProcessFoodOrder': EventHandler<{ email: string; quantity: number; petId: string }, { topic: 'notification'; data: { templateId: string; email: string; templateData: Record<string, unknown> } }>
    'Notification': EventHandler<{ templateId: string; email: string; templateData: Record<string, unknown> }, never>
    'ApiTrigger': ApiRouteHandler<{ pet: { name: string; photoUrl: string }; foodOrder?: { quantity: number } }, ApiResponse<200, { id: string; name: string; photoUrl: string }>, { topic: 'process-food-order'; data: { email: string; quantity: number; petId: string } }>
    'SubscriptionCreatedHandler': EventHandler<never, never>
    'NotificationHandler': EventHandler<never, never>
    'EscalationEngine': EventHandler<never, { topic: 'escalation.evaluate'; data: never }>
    'BillCreatedHandler': EventHandler<never, never>
    'DailySummaryGenerator': CronHandler<never>
    'BillChecker': CronHandler<{ topic: 'bill.overdue'; data: never }>
    'PayBill': ApiRouteHandler<{ paymentAmount?: number; paymentDate?: string }, unknown, never>
    'GetSummary': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetSubscriptions': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetBills': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'EventsStream': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown>, never>
    'DeleteBill': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; deletedBill: { id: string; name: string } }> | ApiResponse<404, { error: string; message: string; details?: Array<string> }>, never>
    'AddSubscription': ApiRouteHandler<{ name: string; amount: number; renewalDay: number }, ApiResponse<200, { id: string; name: string; amount: number; renewalDay: number; isActive: boolean; createdAt: string; updatedAt: string }> | ApiResponse<400, { error: string; message: string; details?: Array<string> }>, { topic: 'subscription.created'; data: never }>
    'AddBill': ApiRouteHandler<{ name: string; amount: number; dueDate: string }, ApiResponse<200, { id: string; name: string; amount: number; dueDate: string; status: 'pending' | 'overdue' | 'paid'; createdAt: string; updatedAt: string }> | ApiResponse<400, { error: string; message: string; details?: Array<string> }>, { topic: 'bill.created'; data: never }>
  }
    
}